# # Maven
# # Build your Java project and run tests with Apache Maven.
# # Add steps that analyze code, save build artifacts, deploy, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger:
# - main

# pool:
#  # pool-name/agent-nameubuntu-latest
#  name: NaveenPCAgent
#  # demands: docker
#  # vmImage: null
#  # pool-name/NaveenPCAgent

# steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'


trigger:
- main

pool:
#  name: Windows Agents
 # name: NaveenPCAgent
 pool-name/NaveenPCAgent

steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '5.11.0'
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
  displayName: 'Restore NuGet packages'

- task: VSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=Release'
    platform: 'Any CPU'
    clean: true
    maximumCpuCount: true
  displayName: 'Build solution'

- task: VSTest@2
  inputs:
    platform: 'Any CPU'
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
     **\$(BuildConfiguration)\*test*.dll
     !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
  displayName: 'Run unit tests'
